# Generated by Django 2.1.15 on 2020-11-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='price',
            new_name='prize',
        ),
    ]
